apiVersion: v1
kind: Secret
metadata:
  name: argo-workflows-server-token
  annotations:
    kubernetes.io/service-account.name: argo-workflows-server
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-workflows-basic-auth
type: Opaque
stringData:
  auth: 'argo:$apr1$Cb2uHNbO$o/5mHoogsjV4UF1nKABSw1'
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-datalake-access
type: Opaque
stringData:
  username: datalake
  password: datalake_poc
