apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: ingress-nginx
name: ingress-nginx
repo: https://kubernetes.github.io/ingress-nginx
version: 4.1.1
releaseName: ingress-nginx
namespace: ingress-nginx
IncludeCRDs: true
valuesInline:
  controller:
    ingressClassResource:
      default: true
    replicaCount: 1
    admissionWebhooks:
      enabled: false
    hostNetwork: true
    service:
      type: NodePort
