apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../applications/ingress-nginx
- ../../applications/minio
- ../../applications/argo-workflows
- ../../applications/dremio
